### ISSUE TITLE
Feature Request: Add a game filter

### ISSUE THREAD

**Issue by xerxes-at** [mxve/plutonium-updater.rs#3]
Since the custom assets for IW5 are around 500MB and each of my server instances is running in its own docker container with no shared Plutonium installation. I would like to be able to limit the game assets to only one game.

**Comment by mxve** [comment]
https://github.com/mxve/plutonium-updater.rs/releases/tag/v0.4.2

-e/--exclude "file|folder"

it matches either full path (with forward slash /) or start of the path,
so to exclude iw5 you'd use -e "storage/iw5", for multiple excludes set the argument multiple times
